stages:
  - build
  - test
  - lint
  - template
  - deploy

variables:
  RELEASE_NAME: my-release
  CHART_PATH: .

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"  # na merge requestu
    - if: $CI_COMMIT_BRANCH == "main"                   # na pushu na main

maven-build:
  stage: build
  script:
    - cd my-java-app
    - mvn compile
  tags:
    - my-runner

maven-test:
  stage: test
  script:
    - cd my-java-app
    - mvn test
  artifacts:
    when: always
    reports:
      junit: my-java-app/target/surefire-reports/TEST-*.xml
  tags:
    - my-runner

maven-package:
  stage: test
  script:
    - cd my-java-app
    - mvn package
  artifacts:
    paths:
      - my-java-app/target/*.jar
  tags:
    - my-runner

helm-lint:
  stage: lint
  script:
    - helm lint $CHART_PATH
  tags:
    - my-runner

helm-template:
  stage: template
  script:
    - helm template $RELEASE_NAME $CHART_PATH
  tags:
    - my-runner

helm-deploy:
  stage: deploy
  script:
    - helm upgrade --install $RELEASE_NAME $CHART_PATH --reset-values
  tags:
    - my-runner
  rules: if: $CI_COMMIT_BRANCH == "main"  # deploy SAMO na main
